### ISSUE TITLE
Convert links to other codes notes to relationships

### ISSUE THREAD

**Issue by strogonoff** [paneron/ics-demo-paneron.github.io#1]
E.g., notes here:

https://github.com/paneron/ics-codes-registry/blob/e031b9e38dc3604c8d125ca0045511b650108d8d/codes/01427f1c-dbac-5bda-9d5d-78de98dd6094.yaml#L9-L13

Should be converted to:

```yaml
data:
  # ...
  relationships:
    - { type: related, to: <uuid corresponding to 91.100.50> }
    - { type: related, to: <uuid corresponding to 93.080.20> }
```
